trackers:
  - name: site
    endpoint: https://site.com/api/torrents/filter
    type: unit3d # Tracker type. Supported types are: unit3d
    client: rtorrent # Client type. Supported clients are: rtorrent
    backup: true # Backup torrents
    tag: true # Tag torrent in client
    ask: true # Ask before backing up
    resend: false # Resend torrents that are already backed up
    headers:
      Authorization: Bearer awesomesecretapikey # Your API key
      Content-Type: application/json
      Accept: application/json
    params:
      sortField: name
      sortDirection: asc
      uploader: coolseeder # Your username
backup:
  type: rclone # Backup type. Supported types are: rclone
  base_path: 'remote:and/a/path/' # Remote path
clients:
  rtorrent:
    socket: /var/run/user/.rtorrent.sock # rtorrent socket
    path: /home/user/torrents/rtorrent/ # rtorrent download path
    label: my-uploads # rtorrent label to apply